//
//  DBColorNames.m
//  DBColorNames
//
//  Created by Daniel Beard on 10/16/14.
//  Copyright (c) 2014 DanielBeard. All rights reserved.
//

/*
 The MIT License (MIT)
 
 Copyright (c) 2014 Daniel Beard
 
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 
 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */

#import "DBColorNames.h"
#import <UIKit/UIKit.h>

static const NSString *kId = @"colorId";

@interface DBColorNames ()

@property (nonatomic, strong) NSDictionary *colorMap;

@end

@implementation DBColorNames

- (instancetype)init {
    self = [super init];
    if (self) {
        [self setupColorMap];
    }
    return self;
}

- (UIColor *)colorFromRGBFloat:(int)rgbValue {
    return [UIColor
            colorWithRed : ((float)((rgbValue & 0xFF0000) >> 16)) / 255.0
            green : ((float)((rgbValue & 0xFF00) >> 8)) / 255.0
            blue : ((float)(rgbValue & 0xFF)) / 255.0
            alpha : 1.0];
}

- (void)setupColorMap {
    self.colorMap = @{
                      @"cloudy blue": @{kId:	@(0xacc2d9)},
                      @"dark pastel green": @{kId:	@(0x56ae57)},
                      @"dust": @{kId:	@(0xb2996e)},
                      @"electric lime": @{kId:	@(0xa8ff04)},
                      @"fresh green": @{kId:	@(0x69d84f)},
                      @"light eggplant": @{kId:	@(0x894585)},
                      @"nasty green": @{kId:	@(0x70b23f)},
                      @"really light blue": @{kId:	@(0xd4ffff)},
                      @"tea": @{kId:	@(0x65ab7c)},
                      @"warm purple": @{kId:	@(0x952e8f)},
                      @"yellowish tan": @{kId:	@(0xfcfc81)},
                      @"cement": @{kId:	@(0xa5a391)},
                      @"dark grass green": @{kId:	@(0x388004)},
                      @"dusty teal": @{kId:	@(0x4c9085)},
                      @"grey teal": @{kId:	@(0x5e9b8a)},
                      @"macaroni and cheese": @{kId:	@(0xefb435)},
                      @"pinkish tan": @{kId:	@(0xd99b82)},
                      @"spruce": @{kId:	@(0x0a5f38)},
                      @"strong blue": @{kId:	@(0x0c06f7)},
                      @"toxic green": @{kId:	@(0x61de2a)},
                      @"windows blue": @{kId:	@(0x3778bf)},
                      @"blue blue": @{kId:	@(0x2242c7)},
                      @"blue with a hint of purple": @{kId:	@(0x533cc6)},
                      @"booger": @{kId:	@(0x9bb53c)},
                      @"bright sea green": @{kId:	@(0x05ffa6)},
                      @"dark green blue": @{kId:	@(0x1f6357)},
                      @"deep turquoise": @{kId:	@(0x017374)},
                      @"green teal": @{kId:	@(0x0cb577)},
                      @"strong pink": @{kId:	@(0xff0789)},
                      @"bland": @{kId:	@(0xafa88b)},
                      @"deep aqua": @{kId:	@(0x08787f)},
                      @"lavender pink": @{kId:	@(0xdd85d7)},
                      @"light moss green": @{kId:	@(0xa6c875)},
                      @"light seafoam green": @{kId:	@(0xa7ffb5)},
                      @"olive yellow": @{kId:	@(0xc2b709)},
                      @"pig pink": @{kId:	@(0xe78ea5)},
                      @"deep lilac": @{kId:	@(0x966ebd)},
                      @"desert": @{kId:	@(0xccad60)},
                      @"dusty lavender": @{kId:	@(0xac86a8)},
                      @"purpley grey": @{kId:	@(0x947e94)},
                      @"purply": @{kId:	@(0x983fb2)},
                      @"candy pink": @{kId:	@(0xff63e9)},
                      @"light pastel green": @{kId:	@(0xb2fba5)},
                      @"boring green": @{kId:	@(0x63b365)},
                      @"kiwi green": @{kId:	@(0x8ee53f)},
                      @"light grey green": @{kId:	@(0xb7e1a1)},
                      @"orange pink": @{kId:	@(0xff6f52)},
                      @"tea green": @{kId:	@(0xbdf8a3)},
                      @"very light brown": @{kId:	@(0xd3b683)},
                      @"egg shell": @{kId:	@(0xfffcc4)},
                      @"eggplant purple": @{kId:	@(0x430541)},
                      @"powder pink": @{kId:	@(0xffb2d0)},
                      @"reddish grey": @{kId:	@(0x997570)},
                      @"baby shit brown": @{kId:	@(0xad900d)},
                      @"liliac": @{kId:	@(0xc48efd)},
                      @"stormy blue": @{kId:	@(0x507b9c)},
                      @"ugly brown": @{kId:	@(0x7d7103)},
                      @"custard": @{kId:	@(0xfffd78)},
                      @"darkish pink": @{kId:	@(0xda467d)},
                      @"deep brown": @{kId:	@(0x410200)},
                      @"greenish beige": @{kId:	@(0xc9d179)},
                      @"manilla": @{kId:	@(0xfffa86)},
                      @"off blue": @{kId:	@(0x5684ae)},
                      @"battleship grey": @{kId:	@(0x6b7c85)},
                      @"browny green": @{kId:	@(0x6f6c0a)},
                      @"bruise": @{kId:	@(0x7e4071)},
                      @"kelley green": @{kId:	@(0x009337)},
                      @"sickly yellow": @{kId:	@(0xd0e429)},
                      @"sunny yellow": @{kId:	@(0xfff917)},
                      @"azul": @{kId:	@(0x1d5dec)},
                      @"darkgreen": @{kId:	@(0x054907)},
                      @"green/yellow": @{kId:	@(0xb5ce08)},
                      @"lichen": @{kId:	@(0x8fb67b)},
                      @"light light green": @{kId:	@(0xc8ffb0)},
                      @"pale gold": @{kId:	@(0xfdde6c)},
                      @"sun yellow": @{kId:	@(0xffdf22)},
                      @"tan green": @{kId:	@(0xa9be70)},
                      @"burple": @{kId:	@(0x6832e3)},
                      @"butterscotch": @{kId:	@(0xfdb147)},
                      @"toupe": @{kId:	@(0xc7ac7d)},
                      @"dark cream": @{kId:	@(0xfff39a)},
                      @"indian red": @{kId:	@(0x850e04)},
                      @"light lavendar": @{kId:	@(0xefc0fe)},
                      @"poison green": @{kId:	@(0x40fd14)},
                      @"baby puke green": @{kId:	@(0xb6c406)},
                      @"bright yellow green": @{kId:	@(0x9dff00)},
                      @"charcoal grey": @{kId:	@(0x3c4142)},
                      @"squash": @{kId:	@(0xf2ab15)},
                      @"cinnamon": @{kId:	@(0xac4f06)},
                      @"light pea green": @{kId:	@(0xc4fe82)},
                      @"radioactive green": @{kId:	@(0x2cfa1f)},
                      @"raw sienna": @{kId:	@(0x9a6200)},
                      @"baby purple": @{kId:	@(0xca9bf7)},
                      @"cocoa": @{kId:	@(0x875f42)},
                      @"light royal blue": @{kId:	@(0x3a2efe)},
                      @"orangeish": @{kId:	@(0xfd8d49)},
                      @"rust brown": @{kId:	@(0x8b3103)},
                      @"sand brown": @{kId:	@(0xcba560)},
                      @"swamp": @{kId:	@(0x698339)},
                      @"tealish green": @{kId:	@(0x0cdc73)},
                      @"burnt siena": @{kId:	@(0xb75203)},
                      @"camo": @{kId:	@(0x7f8f4e)},
                      @"dusk blue": @{kId:	@(0x26538d)},
                      @"fern": @{kId:	@(0x63a950)},
                      @"old rose": @{kId:	@(0xc87f89)},
                      @"pale light green": @{kId:	@(0xb1fc99)},
                      @"peachy pink": @{kId:	@(0xff9a8a)},
                      @"rosy pink": @{kId:	@(0xf6688e)},
                      @"light bluish green": @{kId:	@(0x76fda8)},
                      @"light bright green": @{kId:	@(0x53fe5c)},
                      @"light neon green": @{kId:	@(0x4efd54)},
                      @"light seafoam": @{kId:	@(0xa0febf)},
                      @"tiffany blue": @{kId:	@(0x7bf2da)},
                      @"washed out green": @{kId:	@(0xbcf5a6)},
                      @"browny orange": @{kId:	@(0xca6b02)},
                      @"nice blue": @{kId:	@(0x107ab0)},
                      @"sapphire": @{kId:	@(0x2138ab)},
                      @"greyish teal": @{kId:	@(0x719f91)},
                      @"orangey yellow": @{kId:	@(0xfdb915)},
                      @"parchment": @{kId:	@(0xfefcaf)},
                      @"straw": @{kId:	@(0xfcf679)},
                      @"very dark brown": @{kId:	@(0x1d0200)},
                      @"terracota": @{kId:	@(0xcb6843)},
                      @"ugly blue": @{kId:	@(0x31668a)},
                      @"clear blue": @{kId:	@(0x247afd)},
                      @"creme": @{kId:	@(0xffffb6)},
                      @"foam green": @{kId:	@(0x90fda9)},
                      @"grey/green": @{kId:	@(0x86a17d)},
                      @"light gold": @{kId:	@(0xfddc5c)},
                      @"seafoam blue": @{kId:	@(0x78d1b6)},
                      @"topaz": @{kId:	@(0x13bbaf)},
                      @"violet pink": @{kId:	@(0xfb5ffc)},
                      @"wintergreen": @{kId:	@(0x20f986)},
                      @"yellow tan": @{kId:	@(0xffe36e)},
                      @"dark fuchsia": @{kId:	@(0x9d0759)},
                      @"indigo blue": @{kId:	@(0x3a18b1)},
                      @"light yellowish green": @{kId:	@(0xc2ff89)},
                      @"pale magenta": @{kId:	@(0xd767ad)},
                      @"rich purple": @{kId:	@(0x720058)},
                      @"sunflower yellow": @{kId:	@(0xffda03)},
                      @"green/blue": @{kId:	@(0x01c08d)},
                      @"leather": @{kId:	@(0xac7434)},
                      @"racing green": @{kId:	@(0x014600)},
                      @"vivid purple": @{kId:	@(0x9900fa)},
                      @"dark royal blue": @{kId:	@(0x02066f)},
                      @"hazel": @{kId:	@(0x8e7618)},
                      @"muted pink": @{kId:	@(0xd1768f)},
                      @"booger green": @{kId:	@(0x96b403)},
                      @"canary": @{kId:	@(0xfdff63)},
                      @"cool grey": @{kId:	@(0x95a3a6)},
                      @"dark taupe": @{kId:	@(0x7f684e)},
                      @"darkish purple": @{kId:	@(0x751973)},
                      @"true green": @{kId:	@(0x089404)},
                      @"coral pink": @{kId:	@(0xff6163)},
                      @"dark sage": @{kId:	@(0x598556)},
                      @"dark slate blue": @{kId:	@(0x214761)},
                      @"flat blue": @{kId:	@(0x3c73a8)},
                      @"mushroom": @{kId:	@(0xba9e88)},
                      @"rich blue": @{kId:	@(0x021bf9)},
                      @"dirty purple": @{kId:	@(0x734a65)},
                      @"greenblue": @{kId:	@(0x23c48b)},
                      @"icky green": @{kId:	@(0x8fae22)},
                      @"light khaki": @{kId:	@(0xe6f2a2)},
                      @"warm blue": @{kId:	@(0x4b57db)},
                      @"dark hot pink": @{kId:	@(0xd90166)},
                      @"deep sea blue": @{kId:	@(0x015482)},
                      @"carmine": @{kId:	@(0x9d0216)},
                      @"dark yellow green": @{kId:	@(0x728f02)},
                      @"pale peach": @{kId:	@(0xffe5ad)},
                      @"plum purple": @{kId:	@(0x4e0550)},
                      @"golden rod": @{kId:	@(0xf9bc08)},
                      @"neon red": @{kId:	@(0xff073a)},
                      @"old pink": @{kId:	@(0xc77986)},
                      @"very pale blue": @{kId:	@(0xd6fffe)},
                      @"blood orange": @{kId:	@(0xfe4b03)},
                      @"grapefruit": @{kId:	@(0xfd5956)},
                      @"sand yellow": @{kId:	@(0xfce166)},
                      @"clay brown": @{kId:	@(0xb2713d)},
                      @"dark blue grey": @{kId:	@(0x1f3b4d)},
                      @"flat green": @{kId:	@(0x699d4c)},
                      @"light green blue": @{kId:	@(0x56fca2)},
                      @"warm pink": @{kId:	@(0xfb5581)},
                      @"dodger blue": @{kId:	@(0x3e82fc)},
                      @"gross green": @{kId:	@(0xa0bf16)},
                      @"ice": @{kId:	@(0xd6fffa)},
                      @"metallic blue": @{kId:	@(0x4f738e)},
                      @"pale salmon": @{kId:	@(0xffb19a)},
                      @"sap green": @{kId:	@(0x5c8b15)},
                      @"algae": @{kId:	@(0x54ac68)},
                      @"bluey grey": @{kId:	@(0x89a0b0)},
                      @"greeny grey": @{kId:	@(0x7ea07a)},
                      @"highlighter green": @{kId:	@(0x1bfc06)},
                      @"light light blue": @{kId:	@(0xcafffb)},
                      @"light mint": @{kId:	@(0xb6ffbb)},
                      @"raw umber": @{kId:	@(0xa75e09)},
                      @"vivid blue": @{kId:	@(0x152eff)},
                      @"deep lavender": @{kId:	@(0x8d5eb7)},
                      @"dull teal": @{kId:	@(0x5f9e8f)},
                      @"light greenish blue": @{kId:	@(0x63f7b4)},
                      @"mud green": @{kId:	@(0x606602)},
                      @"pinky": @{kId:	@(0xfc86aa)},
                      @"red wine": @{kId:	@(0x8c0034)},
                      @"shit green": @{kId:	@(0x758000)},
                      @"tan brown": @{kId:	@(0xab7e4c)},
                      @"darkblue": @{kId:	@(0x030764)},
                      @"rosa": @{kId:	@(0xfe86a4)},
                      @"lipstick": @{kId:	@(0xd5174e)},
                      @"pale mauve": @{kId:	@(0xfed0fc)},
                      @"claret": @{kId:	@(0x680018)},
                      @"dandelion": @{kId:	@(0xfedf08)},
                      @"orangered": @{kId:	@(0xfe420f)},
                      @"poop green": @{kId:	@(0x6f7c00)},
                      @"ruby": @{kId:	@(0xca0147)},
                      @"dark": @{kId:	@(0x1b2431)},
                      @"greenish turquoise": @{kId:	@(0x00fbb0)},
                      @"pastel red": @{kId:	@(0xdb5856)},
                      @"piss yellow": @{kId:	@(0xddd618)},
                      @"bright cyan": @{kId:	@(0x41fdfe)},
                      @"dark coral": @{kId:	@(0xcf524e)},
                      @"algae green": @{kId:	@(0x21c36f)},
                      @"darkish red": @{kId:	@(0xa90308)},
                      @"reddy brown": @{kId:	@(0x6e1005)},
                      @"blush pink": @{kId:	@(0xfe828c)},
                      @"camouflage green": @{kId:	@(0x4b6113)},
                      @"lawn green": @{kId:	@(0x4da409)},
                      @"putty": @{kId:	@(0xbeae8a)},
                      @"vibrant blue": @{kId:	@(0x0339f8)},
                      @"dark sand": @{kId:	@(0xa88f59)},
                      @"purple/blue": @{kId:	@(0x5d21d0)},
                      @"saffron": @{kId:	@(0xfeb209)},
                      @"twilight": @{kId:	@(0x4e518b)},
                      @"warm brown": @{kId:	@(0x964e02)},
                      @"bluegrey": @{kId:	@(0x85a3b2)},
                      @"bubble gum pink": @{kId:	@(0xff69af)},
                      @"duck egg blue": @{kId:	@(0xc3fbf4)},
                      @"greenish cyan": @{kId:	@(0x2afeb7)},
                      @"petrol": @{kId:	@(0x005f6a)},
                      @"royal": @{kId:	@(0x0c1793)},
                      @"butter": @{kId:	@(0xffff81)},
                      @"dusty orange": @{kId:	@(0xf0833a)},
                      @"off yellow": @{kId:	@(0xf1f33f)},
                      @"pale olive green": @{kId:	@(0xb1d27b)},
                      @"orangish": @{kId:	@(0xfc824a)},
                      @"leaf": @{kId:	@(0x71aa34)},
                      @"light blue grey": @{kId:	@(0xb7c9e2)},
                      @"dried blood": @{kId:	@(0x4b0101)},
                      @"lightish purple": @{kId:	@(0xa552e6)},
                      @"rusty red": @{kId:	@(0xaf2f0d)},
                      @"lavender blue": @{kId:	@(0x8b88f8)},
                      @"light grass green": @{kId:	@(0x9af764)},
                      @"light mint green": @{kId:	@(0xa6fbb2)},
                      @"sunflower": @{kId:	@(0xffc512)},
                      @"velvet": @{kId:	@(0x750851)},
                      @"brick orange": @{kId:	@(0xc14a09)},
                      @"lightish red": @{kId:	@(0xfe2f4a)},
                      @"pure blue": @{kId:	@(0x0203e2)},
                      @"twilight blue": @{kId:	@(0x0a437a)},
                      @"violet red": @{kId:	@(0xa50055)},
                      @"yellowy brown": @{kId:	@(0xae8b0c)},
                      @"carnation": @{kId:	@(0xfd798f)},
                      @"muddy yellow": @{kId:	@(0xbfac05)},
                      @"dark seafoam green": @{kId:	@(0x3eaf76)},
                      @"deep rose": @{kId:	@(0xc74767)},
                      @"dusty red": @{kId:	@(0xb9484e)},
                      @"grey/blue": @{kId:	@(0x647d8e)},
                      @"lemon lime": @{kId:	@(0xbffe28)},
                      @"purple/pink": @{kId:	@(0xd725de)},
                      @"brown yellow": @{kId:	@(0xb29705)},
                      @"purple brown": @{kId:	@(0x673a3f)},
                      @"wisteria": @{kId:	@(0xa87dc2)},
                      @"banana yellow": @{kId:	@(0xfafe4b)},
                      @"lipstick red": @{kId:	@(0xc0022f)},
                      @"water blue": @{kId:	@(0x0e87cc)},
                      @"brown grey": @{kId:	@(0x8d8468)},
                      @"vibrant purple": @{kId:	@(0xad03de)},
                      @"baby green": @{kId:	@(0x8cff9e)},
                      @"barf green": @{kId:	@(0x94ac02)},
                      @"eggshell blue": @{kId:	@(0xc4fff7)},
                      @"sandy yellow": @{kId:	@(0xfdee73)},
                      @"cool green": @{kId:	@(0x33b864)},
                      @"pale": @{kId:	@(0xfff9d0)},
                      @"blue/grey": @{kId:	@(0x758da3)},
                      @"hot magenta": @{kId:	@(0xf504c9)},
                      @"greyblue": @{kId:	@(0x77a1b5)},
                      @"purpley": @{kId:	@(0x8756e4)},
                      @"baby shit green": @{kId:	@(0x889717)},
                      @"brownish pink": @{kId:	@(0xc27e79)},
                      @"dark aquamarine": @{kId:	@(0x017371)},
                      @"diarrhea": @{kId:	@(0x9f8303)},
                      @"light mustard": @{kId:	@(0xf7d560)},
                      @"pale sky blue": @{kId:	@(0xbdf6fe)},
                      @"turtle green": @{kId:	@(0x75b84f)},
                      @"bright olive": @{kId:	@(0x9cbb04)},
                      @"dark grey blue": @{kId:	@(0x29465b)},
                      @"greeny brown": @{kId:	@(0x696006)},
                      @"lemon green": @{kId:	@(0xadf802)},
                      @"light periwinkle": @{kId:	@(0xc1c6fc)},
                      @"seaweed green": @{kId:	@(0x35ad6b)},
                      @"sunshine yellow": @{kId:	@(0xfffd37)},
                      @"ugly purple": @{kId:	@(0xa442a0)},
                      @"medium pink": @{kId:	@(0xf36196)},
                      @"puke brown": @{kId:	@(0x947706)},
                      @"very light pink": @{kId:	@(0xfff4f2)},
                      @"viridian": @{kId:	@(0x1e9167)},
                      @"bile": @{kId:	@(0xb5c306)},
                      @"faded yellow": @{kId:	@(0xfeff7f)},
                      @"very pale green": @{kId:	@(0xcffdbc)},
                      @"vibrant green": @{kId:	@(0x0add08)},
                      @"bright lime": @{kId:	@(0x87fd05)},
                      @"spearmint": @{kId:	@(0x1ef876)},
                      @"light aquamarine": @{kId:	@(0x7bfdc7)},
                      @"light sage": @{kId:	@(0xbcecac)},
                      @"yellowgreen": @{kId:	@(0xbbf90f)},
                      @"baby poo": @{kId:	@(0xab9004)},
                      @"dark seafoam": @{kId:	@(0x1fb57a)},
                      @"deep teal": @{kId:	@(0x00555a)},
                      @"heather": @{kId:	@(0xa484ac)},
                      @"rust orange": @{kId:	@(0xc45508)},
                      @"dirty blue": @{kId:	@(0x3f829d)},
                      @"fern green": @{kId:	@(0x548d44)},
                      @"bright lilac": @{kId:	@(0xc95efb)},
                      @"weird green": @{kId:	@(0x3ae57f)},
                      @"peacock blue": @{kId:	@(0x016795)},
                      @"avocado green": @{kId:	@(0x87a922)},
                      @"faded orange": @{kId:	@(0xf0944d)},
                      @"grape purple": @{kId:	@(0x5d1451)},
                      @"hot green": @{kId:	@(0x25ff29)},
                      @"lime yellow": @{kId:	@(0xd0fe1d)},
                      @"mango": @{kId:	@(0xffa62b)},
                      @"shamrock": @{kId:	@(0x01b44c)},
                      @"bubblegum": @{kId:	@(0xff6cb5)},
                      @"purplish brown": @{kId:	@(0x6b4247)},
                      @"vomit yellow": @{kId:	@(0xc7c10c)},
                      @"pale cyan": @{kId:	@(0xb7fffa)},
                      @"key lime": @{kId:	@(0xaeff6e)},
                      @"tomato red": @{kId:	@(0xec2d01)},
                      @"lightgreen": @{kId:	@(0x76ff7b)},
                      @"merlot": @{kId:	@(0x730039)},
                      @"night blue": @{kId:	@(0x040348)},
                      @"purpleish pink": @{kId:	@(0xdf4ec8)},
                      @"apple": @{kId:	@(0x6ecb3c)},
                      @"baby poop green": @{kId:	@(0x8f9805)},
                      @"green apple": @{kId:	@(0x5edc1f)},
                      @"heliotrope": @{kId:	@(0xd94ff5)},
                      @"yellow/green": @{kId:	@(0xc8fd3d)},
                      @"almost black": @{kId:	@(0x070d0d)},
                      @"cool blue": @{kId:	@(0x4984b8)},
                      @"leafy green": @{kId:	@(0x51b73b)},
                      @"mustard brown": @{kId:	@(0xac7e04)},
                      @"dusk": @{kId:	@(0x4e5481)},
                      @"dull brown": @{kId:	@(0x876e4b)},
                      @"frog green": @{kId:	@(0x58bc08)},
                      @"vivid green": @{kId:	@(0x2fef10)},
                      @"bright light green": @{kId:	@(0x2dfe54)},
                      @"fluro green": @{kId:	@(0x0aff02)},
                      @"kiwi": @{kId:	@(0x9cef43)},
                      @"seaweed": @{kId:	@(0x18d17b)},
                      @"navy green": @{kId:	@(0x35530a)},
                      @"ultramarine blue": @{kId:	@(0x1805db)},
                      @"iris": @{kId:	@(0x6258c4)},
                      @"pastel orange": @{kId:	@(0xff964f)},
                      @"yellowish orange": @{kId:	@(0xffab0f)},
                      @"perrywinkle": @{kId:	@(0x8f8ce7)},
                      @"tealish": @{kId:	@(0x24bca8)},
                      @"dark plum": @{kId:	@(0x3f012c)},
                      @"pear": @{kId:	@(0xcbf85f)},
                      @"pinkish orange": @{kId:	@(0xff724c)},
                      @"midnight purple": @{kId:	@(0x280137)},
                      @"light urple": @{kId:	@(0xb36ff6)},
                      @"dark mint": @{kId:	@(0x48c072)},
                      @"greenish tan": @{kId:	@(0xbccb7a)},
                      @"light burgundy": @{kId:	@(0xa8415b)},
                      @"turquoise blue": @{kId:	@(0x06b1c4)},
                      @"ugly pink": @{kId:	@(0xcd7584)},
                      @"sandy": @{kId:	@(0xf1da7a)},
                      @"electric pink": @{kId:	@(0xff0490)},
                      @"muted purple": @{kId:	@(0x805b87)},
                      @"mid green": @{kId:	@(0x50a747)},
                      @"greyish": @{kId:	@(0xa8a495)},
                      @"neon yellow": @{kId:	@(0xcfff04)},
                      @"banana": @{kId:	@(0xffff7e)},
                      @"carnation pink": @{kId:	@(0xff7fa7)},
                      @"tomato": @{kId:	@(0xef4026)},
                      @"sea": @{kId:	@(0x3c9992)},
                      @"muddy brown": @{kId:	@(0x886806)},
                      @"turquoise green": @{kId:	@(0x04f489)},
                      @"buff": @{kId:	@(0xfef69e)},
                      @"fawn": @{kId:	@(0xcfaf7b)},
                      @"muted blue": @{kId:	@(0x3b719f)},
                      @"pale rose": @{kId:	@(0xfdc1c5)},
                      @"dark mint green": @{kId:	@(0x20c073)},
                      @"amethyst": @{kId:	@(0x9b5fc0)},
                      @"blue/green": @{kId:	@(0x0f9b8e)},
                      @"chestnut": @{kId:	@(0x742802)},
                      @"sick green": @{kId:	@(0x9db92c)},
                      @"pea": @{kId:	@(0xa4bf20)},
                      @"rusty orange": @{kId:	@(0xcd5909)},
                      @"stone": @{kId:	@(0xada587)},
                      @"rose red": @{kId:	@(0xbe013c)},
                      @"pale aqua": @{kId:	@(0xb8ffeb)},
                      @"deep orange": @{kId:	@(0xdc4d01)},
                      @"earth": @{kId:	@(0xa2653e)},
                      @"mossy green": @{kId:	@(0x638b27)},
                      @"grassy green": @{kId:	@(0x419c03)},
                      @"pale lime green": @{kId:	@(0xb1ff65)},
                      @"light grey blue": @{kId:	@(0x9dbcd4)},
                      @"pale grey": @{kId:	@(0xfdfdfe)},
                      @"asparagus": @{kId:	@(0x77ab56)},
                      @"blueberry": @{kId:	@(0x464196)},
                      @"purple red": @{kId:	@(0x990147)},
                      @"pale lime": @{kId:	@(0xbefd73)},
                      @"greenish teal": @{kId:	@(0x32bf84)},
                      @"caramel": @{kId:	@(0xaf6f09)},
                      @"deep magenta": @{kId:	@(0xa0025c)},
                      @"light peach": @{kId:	@(0xffd8b1)},
                      @"milk chocolate": @{kId:	@(0x7f4e1e)},
                      @"ocher": @{kId:	@(0xbf9b0c)},
                      @"off green": @{kId:	@(0x6ba353)},
                      @"purply pink": @{kId:	@(0xf075e6)},
                      @"lightblue": @{kId:	@(0x7bc8f6)},
                      @"dusky blue": @{kId:	@(0x475f94)},
                      @"golden": @{kId:	@(0xf5bf03)},
                      @"light beige": @{kId:	@(0xfffeb6)},
                      @"butter yellow": @{kId:	@(0xfffd74)},
                      @"dusky purple": @{kId:	@(0x895b7b)},
                      @"french blue": @{kId:	@(0x436bad)},
                      @"ugly yellow": @{kId:	@(0xd0c101)},
                      @"greeny yellow": @{kId:	@(0xc6f808)},
                      @"orangish red": @{kId:	@(0xf43605)},
                      @"shamrock green": @{kId:	@(0x02c14d)},
                      @"orangish brown": @{kId:	@(0xb25f03)},
                      @"tree green": @{kId:	@(0x2a7e19)},
                      @"deep violet": @{kId:	@(0x490648)},
                      @"gunmetal": @{kId:	@(0x536267)},
                      @"blue/purple": @{kId:	@(0x5a06ef)},
                      @"cherry": @{kId:	@(0xcf0234)},
                      @"sandy brown": @{kId:	@(0xc4a661)},
                      @"warm grey": @{kId:	@(0x978a84)},
                      @"dark indigo": @{kId:	@(0x1f0954)},
                      @"midnight": @{kId:	@(0x03012d)},
                      @"bluey green": @{kId:	@(0x2bb179)},
                      @"grey pink": @{kId:	@(0xc3909b)},
                      @"soft purple": @{kId:	@(0xa66fb5)},
                      @"blood": @{kId:	@(0x770001)},
                      @"brown red": @{kId:	@(0x922b05)},
                      @"medium grey": @{kId:	@(0x7d7f7c)},
                      @"berry": @{kId:	@(0x990f4b)},
                      @"poo": @{kId:	@(0x8f7303)},
                      @"purpley pink": @{kId:	@(0xc83cb9)},
                      @"light salmon": @{kId:	@(0xfea993)},
                      @"snot": @{kId:	@(0xacbb0d)},
                      @"easter purple": @{kId:	@(0xc071fe)},
                      @"light yellow green": @{kId:	@(0xccfd7f)},
                      @"dark navy blue": @{kId:	@(0x00022e)},
                      @"drab": @{kId:	@(0x828344)},
                      @"light rose": @{kId:	@(0xffc5cb)},
                      @"rouge": @{kId:	@(0xab1239)},
                      @"purplish red": @{kId:	@(0xb0054b)},
                      @"slime green": @{kId:	@(0x99cc04)},
                      @"baby poop": @{kId:	@(0x937c00)},
                      @"irish green": @{kId:	@(0x019529)},
                      @"pink/purple": @{kId:	@(0xef1de7)},
                      @"dark navy": @{kId:	@(0x000435)},
                      @"greeny blue": @{kId:	@(0x42b395)},
                      @"light plum": @{kId:	@(0x9d5783)},
                      @"pinkish grey": @{kId:	@(0xc8aca9)},
                      @"dirty orange": @{kId:	@(0xc87606)},
                      @"rust red": @{kId:	@(0xaa2704)},
                      @"pale lilac": @{kId:	@(0xe4cbff)},
                      @"orangey red": @{kId:	@(0xfa4224)},
                      @"primary blue": @{kId:	@(0x0804f9)},
                      @"kermit green": @{kId:	@(0x5cb200)},
                      @"brownish purple": @{kId:	@(0x76424e)},
                      @"murky green": @{kId:	@(0x6c7a0e)},
                      @"wheat": @{kId:	@(0xfbdd7e)},
                      @"very dark purple": @{kId:	@(0x2a0134)},
                      @"bottle green": @{kId:	@(0x044a05)},
                      @"watermelon": @{kId:	@(0xfd4659)},
                      @"deep sky blue": @{kId:	@(0x0d75f8)},
                      @"fire engine red": @{kId:	@(0xfe0002)},
                      @"yellow ochre": @{kId:	@(0xcb9d06)},
                      @"pumpkin orange": @{kId:	@(0xfb7d07)},
                      @"pale olive": @{kId:	@(0xb9cc81)},
                      @"light lilac": @{kId:	@(0xedc8ff)},
                      @"lightish green": @{kId:	@(0x61e160)},
                      @"carolina blue": @{kId:	@(0x8ab8fe)},
                      @"mulberry": @{kId:	@(0x920a4e)},
                      @"shocking pink": @{kId:	@(0xfe02a2)},
                      @"auburn": @{kId:	@(0x9a3001)},
                      @"bright lime green": @{kId:	@(0x65fe08)},
                      @"celadon": @{kId:	@(0xbefdb7)},
                      @"pinkish brown": @{kId:	@(0xb17261)},
                      @"poo brown": @{kId:	@(0x885f01)},
                      @"bright sky blue": @{kId:	@(0x02ccfe)},
                      @"celery": @{kId:	@(0xc1fd95)},
                      @"dirt brown": @{kId:	@(0x836539)},
                      @"strawberry": @{kId:	@(0xfb2943)},
                      @"dark lime": @{kId:	@(0x84b701)},
                      @"copper": @{kId:	@(0xb66325)},
                      @"medium brown": @{kId:	@(0x7f5112)},
                      @"muted green": @{kId:	@(0x5fa052)},
                      @"robin's egg": @{kId:	@(0x6dedfd)},
                      @"bright aqua": @{kId:	@(0x0bf9ea)},
                      @"bright lavender": @{kId:	@(0xc760ff)},
                      @"ivory": @{kId:	@(0xffffcb)},
                      @"very light purple": @{kId:	@(0xf6cefc)},
                      @"light navy": @{kId:	@(0x155084)},
                      @"pink red": @{kId:	@(0xf5054f)},
                      @"olive brown": @{kId:	@(0x645403)},
                      @"poop brown": @{kId:	@(0x7a5901)},
                      @"mustard green": @{kId:	@(0xa8b504)},
                      @"ocean green": @{kId:	@(0x3d9973)},
                      @"very dark blue": @{kId:	@(0x000133)},
                      @"dusty green": @{kId:	@(0x76a973)},
                      @"light navy blue": @{kId:	@(0x2e5a88)},
                      @"minty green": @{kId:	@(0x0bf77d)},
                      @"adobe": @{kId:	@(0xbd6c48)},
                      @"barney": @{kId:	@(0xac1db8)},
                      @"jade green": @{kId:	@(0x2baf6a)},
                      @"bright light blue": @{kId:	@(0x26f7fd)},
                      @"light lime": @{kId:	@(0xaefd6c)},
                      @"dark khaki": @{kId:	@(0x9b8f55)},
                      @"orange yellow": @{kId:	@(0xffad01)},
                      @"ocre": @{kId:	@(0xc69c04)},
                      @"maize": @{kId:	@(0xf4d054)},
                      @"faded pink": @{kId:	@(0xde9dac)},
                      @"british racing green": @{kId:	@(0x05480d)},
                      @"sandstone": @{kId:	@(0xc9ae74)},
                      @"mud brown": @{kId:	@(0x60460f)},
                      @"light sea green": @{kId:	@(0x98f6b0)},
                      @"robin egg blue": @{kId:	@(0x8af1fe)},
                      @"aqua marine": @{kId:	@(0x2ee8bb)},
                      @"dark sea green": @{kId:	@(0x11875d)},
                      @"soft pink": @{kId:	@(0xfdb0c0)},
                      @"orangey brown": @{kId:	@(0xb16002)},
                      @"cherry red": @{kId:	@(0xf7022a)},
                      @"burnt yellow": @{kId:	@(0xd5ab09)},
                      @"brownish grey": @{kId:	@(0x86775f)},
                      @"camel": @{kId:	@(0xc69f59)},
                      @"purplish grey": @{kId:	@(0x7a687f)},
                      @"marine": @{kId:	@(0x042e60)},
                      @"greyish pink": @{kId:	@(0xc88d94)},
                      @"pale turquoise": @{kId:	@(0xa5fbd5)},
                      @"pastel yellow": @{kId:	@(0xfffe71)},
                      @"bluey purple": @{kId:	@(0x6241c7)},
                      @"canary yellow": @{kId:	@(0xfffe40)},
                      @"faded red": @{kId:	@(0xd3494e)},
                      @"sepia": @{kId:	@(0x985e2b)},
                      @"coffee": @{kId:	@(0xa6814c)},
                      @"bright magenta": @{kId:	@(0xff08e8)},
                      @"mocha": @{kId:	@(0x9d7651)},
                      @"ecru": @{kId:	@(0xfeffca)},
                      @"purpleish": @{kId:	@(0x98568d)},
                      @"cranberry": @{kId:	@(0x9e003a)},
                      @"darkish green": @{kId:	@(0x287c37)},
                      @"brown orange": @{kId:	@(0xb96902)},
                      @"dusky rose": @{kId:	@(0xba6873)},
                      @"melon": @{kId:	@(0xff7855)},
                      @"sickly green": @{kId:	@(0x94b21c)},
                      @"silver": @{kId:	@(0xc5c9c7)},
                      @"purply blue": @{kId:	@(0x661aee)},
                      @"purpleish blue": @{kId:	@(0x6140ef)},
                      @"hospital green": @{kId:	@(0x9be5aa)},
                      @"shit brown": @{kId:	@(0x7b5804)},
                      @"mid blue": @{kId:	@(0x276ab3)},
                      @"amber": @{kId:	@(0xfeb308)},
                      @"easter green": @{kId:	@(0x8cfd7e)},
                      @"soft blue": @{kId:	@(0x6488ea)},
                      @"cerulean blue": @{kId:	@(0x056eee)},
                      @"golden brown": @{kId:	@(0xb27a01)},
                      @"bright turquoise": @{kId:	@(0x0ffef9)},
                      @"red pink": @{kId:	@(0xfa2a55)},
                      @"red purple": @{kId:	@(0x820747)},
                      @"greyish brown": @{kId:	@(0x7a6a4f)},
                      @"vermillion": @{kId:	@(0xf4320c)},
                      @"russet": @{kId:	@(0xa13905)},
                      @"steel grey": @{kId:	@(0x6f828a)},
                      @"lighter purple": @{kId:	@(0xa55af4)},
                      @"bright violet": @{kId:	@(0xad0afd)},
                      @"prussian blue": @{kId:	@(0x004577)},
                      @"slate green": @{kId:	@(0x658d6d)},
                      @"dirty pink": @{kId:	@(0xca7b80)},
                      @"dark blue green": @{kId:	@(0x005249)},
                      @"pine": @{kId:	@(0x2b5d34)},
                      @"yellowy green": @{kId:	@(0xbff128)},
                      @"dark gold": @{kId:	@(0xb59410)},
                      @"bluish": @{kId:	@(0x2976bb)},
                      @"darkish blue": @{kId:	@(0x014182)},
                      @"dull red": @{kId:	@(0xbb3f3f)},
                      @"pinky red": @{kId:	@(0xfc2647)},
                      @"bronze": @{kId:	@(0xa87900)},
                      @"pale teal": @{kId:	@(0x82cbb2)},
                      @"military green": @{kId:	@(0x667c3e)},
                      @"barbie pink": @{kId:	@(0xfe46a5)},
                      @"bubblegum pink": @{kId:	@(0xfe83cc)},
                      @"pea soup green": @{kId:	@(0x94a617)},
                      @"dark mustard": @{kId:	@(0xa88905)},
                      @"shit": @{kId:	@(0x7f5f00)},
                      @"medium purple": @{kId:	@(0x9e43a2)},
                      @"very dark green": @{kId:	@(0x062e03)},
                      @"dirt": @{kId:	@(0x8a6e45)},
                      @"dusky pink": @{kId:	@(0xcc7a8b)},
                      @"red violet": @{kId:	@(0x9e0168)},
                      @"lemon yellow": @{kId:	@(0xfdff38)},
                      @"pistachio": @{kId:	@(0xc0fa8b)},
                      @"dull yellow": @{kId:	@(0xeedc5b)},
                      @"dark lime green": @{kId:	@(0x7ebd01)},
                      @"denim blue": @{kId:	@(0x3b5b92)},
                      @"teal blue": @{kId:	@(0x01889f)},
                      @"lightish blue": @{kId:	@(0x3d7afd)},
                      @"purpley blue": @{kId:	@(0x5f34e7)},
                      @"light indigo": @{kId:	@(0x6d5acf)},
                      @"swamp green": @{kId:	@(0x748500)},
                      @"brown green": @{kId:	@(0x706c11)},
                      @"dark maroon": @{kId:	@(0x3c0008)},
                      @"hot purple": @{kId:	@(0xcb00f5)},
                      @"dark forest green": @{kId:	@(0x002d04)},
                      @"faded blue": @{kId:	@(0x658cbb)},
                      @"drab green": @{kId:	@(0x749551)},
                      @"light lime green": @{kId:	@(0xb9ff66)},
                      @"snot green": @{kId:	@(0x9dc100)},
                      @"yellowish": @{kId:	@(0xfaee66)},
                      @"light blue green": @{kId:	@(0x7efbb3)},
                      @"bordeaux": @{kId:	@(0x7b002c)},
                      @"light mauve": @{kId:	@(0xc292a1)},
                      @"ocean": @{kId:	@(0x017b92)},
                      @"marigold": @{kId:	@(0xfcc006)},
                      @"muddy green": @{kId:	@(0x657432)},
                      @"dull orange": @{kId:	@(0xd8863b)},
                      @"steel": @{kId:	@(0x738595)},
                      @"electric purple": @{kId:	@(0xaa23ff)},
                      @"fluorescent green": @{kId:	@(0x08ff08)},
                      @"yellowish brown": @{kId:	@(0x9b7a01)},
                      @"blush": @{kId:	@(0xf29e8e)},
                      @"soft green": @{kId:	@(0x6fc276)},
                      @"bright orange": @{kId:	@(0xff5b00)},
                      @"lemon": @{kId:	@(0xfdff52)},
                      @"purple grey": @{kId:	@(0x866f85)},
                      @"acid green": @{kId:	@(0x8ffe09)},
                      @"pale lavender": @{kId:	@(0xeecffe)},
                      @"violet blue": @{kId:	@(0x510ac9)},
                      @"light forest green": @{kId:	@(0x4f9153)},
                      @"burnt red": @{kId:	@(0x9f2305)},
                      @"khaki green": @{kId:	@(0x728639)},
                      @"cerise": @{kId:	@(0xde0c62)},
                      @"faded purple": @{kId:	@(0x916e99)},
                      @"apricot": @{kId:	@(0xffb16d)},
                      @"dark olive green": @{kId:	@(0x3c4d03)},
                      @"grey brown": @{kId:	@(0x7f7053)},
                      @"green grey": @{kId:	@(0x77926f)},
                      @"true blue": @{kId:	@(0x010fcc)},
                      @"pale violet": @{kId:	@(0xceaefa)},
                      @"periwinkle blue": @{kId:	@(0x8f99fb)},
                      @"light sky blue": @{kId:	@(0xc6fcff)},
                      @"blurple": @{kId:	@(0x5539cc)},
                      @"green brown": @{kId:	@(0x544e03)},
                      @"bluegreen": @{kId:	@(0x017a79)},
                      @"bright teal": @{kId:	@(0x01f9c6)},
                      @"brownish yellow": @{kId:	@(0xc9b003)},
                      @"pea soup": @{kId:	@(0x929901)},
                      @"forest": @{kId:	@(0x0b5509)},
                      @"barney purple": @{kId:	@(0xa00498)},
                      @"ultramarine": @{kId:	@(0x2000b1)},
                      @"purplish": @{kId:	@(0x94568c)},
                      @"puke yellow": @{kId:	@(0xc2be0e)},
                      @"bluish grey": @{kId:	@(0x748b97)},
                      @"dark periwinkle": @{kId:	@(0x665fd1)},
                      @"dark lilac": @{kId:	@(0x9c6da5)},
                      @"reddish": @{kId:	@(0xc44240)},
                      @"light maroon": @{kId:	@(0xa24857)},
                      @"dusty purple": @{kId:	@(0x825f87)},
                      @"terra cotta": @{kId:	@(0xc9643b)},
                      @"avocado": @{kId:	@(0x90b134)},
                      @"marine blue": @{kId:	@(0x01386a)},
                      @"teal green": @{kId:	@(0x25a36f)},
                      @"slate grey": @{kId:	@(0x59656d)},
                      @"lighter green": @{kId:	@(0x75fd63)},
                      @"electric green": @{kId:	@(0x21fc0d)},
                      @"dusty blue": @{kId:	@(0x5a86ad)},
                      @"golden yellow": @{kId:	@(0xfec615)},
                      @"bright yellow": @{kId:	@(0xfffd01)},
                      @"light lavender": @{kId:	@(0xdfc5fe)},
                      @"umber": @{kId:	@(0xb26400)},
                      @"poop": @{kId:	@(0x7f5e00)},
                      @"dark peach": @{kId:	@(0xde7e5d)},
                      @"jungle green": @{kId:	@(0x048243)},
                      @"eggshell": @{kId:	@(0xffffd4)},
                      @"denim": @{kId:	@(0x3b638c)},
                      @"yellow brown": @{kId:	@(0xb79400)},
                      @"dull purple": @{kId:	@(0x84597e)},
                      @"chocolate brown": @{kId:	@(0x411900)},
                      @"wine red": @{kId:	@(0x7b0323)},
                      @"neon blue": @{kId:	@(0x04d9ff)},
                      @"dirty green": @{kId:	@(0x667e2c)},
                      @"light tan": @{kId:	@(0xfbeeac)},
                      @"ice blue": @{kId:	@(0xd7fffe)},
                      @"cadet blue": @{kId:	@(0x4e7496)},
                      @"dark mauve": @{kId:	@(0x874c62)},
                      @"very light blue": @{kId:	@(0xd5ffff)},
                      @"grey purple": @{kId:	@(0x826d8c)},
                      @"pastel pink": @{kId:	@(0xffbacd)},
                      @"very light green": @{kId:	@(0xd1ffbd)},
                      @"dark sky blue": @{kId:	@(0x448ee4)},
                      @"evergreen": @{kId:	@(0x05472a)},
                      @"dull pink": @{kId:	@(0xd5869d)},
                      @"aubergine": @{kId:	@(0x3d0734)},
                      @"mahogany": @{kId:	@(0x4a0100)},
                      @"reddish orange": @{kId:	@(0xf8481c)},
                      @"deep green": @{kId:	@(0x02590f)},
                      @"vomit green": @{kId:	@(0x89a203)},
                      @"purple pink": @{kId:	@(0xe03fd8)},
                      @"dusty pink": @{kId:	@(0xd58a94)},
                      @"faded green": @{kId:	@(0x7bb274)},
                      @"camo green": @{kId:	@(0x526525)},
                      @"pinky purple": @{kId:	@(0xc94cbe)},
                      @"pink purple": @{kId:	@(0xdb4bda)},
                      @"brownish red": @{kId:	@(0x9e3623)},
                      @"dark rose": @{kId:	@(0xb5485d)},
                      @"mud": @{kId:	@(0x735c12)},
                      @"brownish": @{kId:	@(0x9c6d57)},
                      @"emerald green": @{kId:	@(0x028f1e)},
                      @"pale brown": @{kId:	@(0xb1916e)},
                      @"dull blue": @{kId:	@(0x49759c)},
                      @"burnt umber": @{kId:	@(0xa0450e)},
                      @"medium green": @{kId:	@(0x39ad48)},
                      @"clay": @{kId:	@(0xb66a50)},
                      @"light aqua": @{kId:	@(0x8cffdb)},
                      @"light olive green": @{kId:	@(0xa4be5c)},
                      @"brownish orange": @{kId:	@(0xcb7723)},
                      @"dark aqua": @{kId:	@(0x05696b)},
                      @"purplish pink": @{kId:	@(0xce5dae)},
                      @"dark salmon": @{kId:	@(0xc85a53)},
                      @"greenish grey": @{kId:	@(0x96ae8d)},
                      @"jade": @{kId:	@(0x1fa774)},
                      @"ugly green": @{kId:	@(0x7a9703)},
                      @"dark beige": @{kId:	@(0xac9362)},
                      @"emerald": @{kId:	@(0x01a049)},
                      @"pale red": @{kId:	@(0xd9544d)},
                      @"light magenta": @{kId:	@(0xfa5ff7)},
                      @"sky": @{kId:	@(0x82cafc)},
                      @"light cyan": @{kId:	@(0xacfffc)},
                      @"yellow orange": @{kId:	@(0xfcb001)},
                      @"reddish purple": @{kId:	@(0x910951)},
                      @"reddish pink": @{kId:	@(0xfe2c54)},
                      @"orchid": @{kId:	@(0xc875c4)},
                      @"dirty yellow": @{kId:	@(0xcdc50a)},
                      @"orange red": @{kId:	@(0xfd411e)},
                      @"deep red": @{kId:	@(0x9a0200)},
                      @"orange brown": @{kId:	@(0xbe6400)},
                      @"cobalt blue": @{kId:	@(0x030aa7)},
                      @"neon pink": @{kId:	@(0xfe019a)},
                      @"rose pink": @{kId:	@(0xf7879a)},
                      @"greyish purple": @{kId:	@(0x887191)},
                      @"raspberry": @{kId:	@(0xb00149)},
                      @"aqua green": @{kId:	@(0x12e193)},
                      @"salmon pink": @{kId:	@(0xfe7b7c)},
                      @"tangerine": @{kId:	@(0xff9408)},
                      @"brownish green": @{kId:	@(0x6a6e09)},
                      @"red brown": @{kId:	@(0x8b2e16)},
                      @"greenish brown": @{kId:	@(0x696112)},
                      @"pumpkin": @{kId:	@(0xe17701)},
                      @"pine green": @{kId:	@(0x0a481e)},
                      @"charcoal": @{kId:	@(0x343837)},
                      @"baby pink": @{kId:	@(0xffb7ce)},
                      @"cornflower": @{kId:	@(0x6a79f7)},
                      @"blue violet": @{kId:	@(0x5d06e9)},
                      @"chocolate": @{kId:	@(0x3d1c02)},
                      @"greyish green": @{kId:	@(0x82a67d)},
                      @"scarlet": @{kId:	@(0xbe0119)},
                      @"green yellow": @{kId:	@(0xc9ff27)},
                      @"dark olive": @{kId:	@(0x373e02)},
                      @"sienna": @{kId:	@(0xa9561e)},
                      @"pastel purple": @{kId:	@(0xcaa0ff)},
                      @"terracotta": @{kId:	@(0xca6641)},
                      @"aqua blue": @{kId:	@(0x02d8e9)},
                      @"sage green": @{kId:	@(0x88b378)},
                      @"blood red": @{kId:	@(0x980002)},
                      @"deep pink": @{kId:	@(0xcb0162)},
                      @"grass": @{kId:	@(0x5cac2d)},
                      @"moss": @{kId:	@(0x769958)},
                      @"pastel blue": @{kId:	@(0xa2bffe)},
                      @"bluish green": @{kId:	@(0x10a674)},
                      @"green blue": @{kId:	@(0x06b48b)},
                      @"dark tan": @{kId:	@(0xaf884a)},
                      @"greenish blue": @{kId:	@(0x0b8b87)},
                      @"pale orange": @{kId:	@(0xffa756)},
                      @"vomit": @{kId:	@(0xa2a415)},
                      @"forrest green": @{kId:	@(0x154406)},
                      @"dark lavender": @{kId:	@(0x856798)},
                      @"dark violet": @{kId:	@(0x34013f)},
                      @"purple blue": @{kId:	@(0x632de9)},
                      @"dark cyan": @{kId:	@(0x0a888a)},
                      @"olive drab": @{kId:	@(0x6f7632)},
                      @"pinkish": @{kId:	@(0xd46a7e)},
                      @"cobalt": @{kId:	@(0x1e488f)},
                      @"neon purple": @{kId:	@(0xbc13fe)},
                      @"light turquoise": @{kId:	@(0x7ef4cc)},
                      @"apple green": @{kId:	@(0x76cd26)},
                      @"dull green": @{kId:	@(0x74a662)},
                      @"wine": @{kId:	@(0x80013f)},
                      @"powder blue": @{kId:	@(0xb1d1fc)},
                      @"off white": @{kId:	@(0xffffe4)},
                      @"electric blue": @{kId:	@(0x0652ff)},
                      @"dark turquoise": @{kId:	@(0x045c5a)},
                      @"blue purple": @{kId:	@(0x5729ce)},
                      @"azure": @{kId:	@(0x069af3)},
                      @"bright red": @{kId:	@(0xff000d)},
                      @"pinkish red": @{kId:	@(0xf10c45)},
                      @"cornflower blue": @{kId:	@(0x5170d7)},
                      @"light olive": @{kId:	@(0xacbf69)},
                      @"grape": @{kId:	@(0x6c3461)},
                      @"greyish blue": @{kId:	@(0x5e819d)},
                      @"purplish blue": @{kId:	@(0x601ef9)},
                      @"yellowish green": @{kId:	@(0xb0dd16)},
                      @"greenish yellow": @{kId:	@(0xcdfd02)},
                      @"medium blue": @{kId:	@(0x2c6fbb)},
                      @"dusty rose": @{kId:	@(0xc0737a)},
                      @"light violet": @{kId:	@(0xd6b4fc)},
                      @"midnight blue": @{kId:	@(0x020035)},
                      @"bluish purple": @{kId:	@(0x703be7)},
                      @"red orange": @{kId:	@(0xfd3c06)},
                      @"dark magenta": @{kId:	@(0x960056)},
                      @"greenish": @{kId:	@(0x40a368)},
                      @"ocean blue": @{kId:	@(0x03719c)},
                      @"coral": @{kId:	@(0xfc5a50)},
                      @"cream": @{kId:	@(0xffffc2)},
                      @"reddish brown": @{kId:	@(0x7f2b0a)},
                      @"burnt sienna": @{kId:	@(0xb04e0f)},
                      @"brick": @{kId:	@(0xa03623)},
                      @"sage": @{kId:	@(0x87ae73)},
                      @"grey green": @{kId:	@(0x789b73)},
                      @"white": @{kId:	@(0xffffff)},
                      @"robin's egg blue": @{kId:	@(0x98eff9)},
                      @"moss green": @{kId:	@(0x658b38)},
                      @"steel blue": @{kId:	@(0x5a7d9a)},
                      @"eggplant": @{kId:	@(0x380835)},
                      @"light yellow": @{kId:	@(0xfffe7a)},
                      @"leaf green": @{kId:	@(0x5ca904)},
                      @"light grey": @{kId:	@(0xd8dcd6)},
                      @"puke": @{kId:	@(0xa5a502)},
                      @"pinkish purple": @{kId:	@(0xd648d7)},
                      @"sea blue": @{kId:	@(0x047495)},
                      @"pale purple": @{kId:	@(0xb790d4)},
                      @"slate blue": @{kId:	@(0x5b7c99)},
                      @"blue grey": @{kId:	@(0x607c8e)},
                      @"hunter green": @{kId:	@(0x0b4008)},
                      @"fuchsia": @{kId:	@(0xed0dd9)},
                      @"crimson": @{kId:	@(0x8c000f)},
                      @"pale yellow": @{kId:	@(0xffff84)},
                      @"ochre": @{kId:	@(0xbf9005)},
                      @"mustard yellow": @{kId:	@(0xd2bd0a)},
                      @"light red": @{kId:	@(0xff474c)},
                      @"cerulean": @{kId:	@(0x0485d1)},
                      @"pale pink": @{kId:	@(0xffcfdc)},
                      @"deep blue": @{kId:	@(0x040273)},
                      @"rust": @{kId:	@(0xa83c09)},
                      @"light teal": @{kId:	@(0x90e4c1)},
                      @"slate": @{kId:	@(0x516572)},
                      @"goldenrod": @{kId:	@(0xfac205)},
                      @"dark yellow": @{kId:	@(0xd5b60a)},
                      @"dark grey": @{kId:	@(0x363737)},
                      @"army green": @{kId:	@(0x4b5d16)},
                      @"grey blue": @{kId:	@(0x6b8ba4)},
                      @"seafoam": @{kId:	@(0x80f9ad)},
                      @"puce": @{kId:	@(0xa57e52)},
                      @"spring green": @{kId:	@(0xa9f971)},
                      @"dark orange": @{kId:	@(0xc65102)},
                      @"sand": @{kId:	@(0xe2ca76)},
                      @"pastel green": @{kId:	@(0xb0ff9d)},
                      @"mint": @{kId:	@(0x9ffeb0)},
                      @"light orange": @{kId:	@(0xfdaa48)},
                      @"bright pink": @{kId:	@(0xfe01b1)},
                      @"chartreuse": @{kId:	@(0xc1f80a)},
                      @"deep purple": @{kId:	@(0x36013f)},
                      @"dark brown": @{kId:	@(0x341c02)},
                      @"taupe": @{kId:	@(0xb9a281)},
                      @"pea green": @{kId:	@(0x8eab12)},
                      @"puke green": @{kId:	@(0x9aae07)},
                      @"kelly green": @{kId:	@(0x02ab2e)},
                      @"seafoam green": @{kId:	@(0x7af9ab)},
                      @"blue green": @{kId:	@(0x137e6d)},
                      @"khaki": @{kId:	@(0xaaa662)},
                      @"burgundy": @{kId:	@(0x610023)},
                      @"dark teal": @{kId:	@(0x014d4e)},
                      @"brick red": @{kId:	@(0x8f1402)},
                      @"royal purple": @{kId:	@(0x4b006e)},
                      @"plum": @{kId:	@(0x580f41)},
                      @"mint green": @{kId:	@(0x8fff9f)},
                      @"gold": @{kId:	@(0xdbb40c)},
                      @"baby blue": @{kId:	@(0xa2cffe)},
                      @"yellow green": @{kId:	@(0xc0fb2d)},
                      @"bright purple": @{kId:	@(0xbe03fd)},
                      @"dark red": @{kId:	@(0x840000)},
                      @"pale blue": @{kId:	@(0xd0fefe)},
                      @"grass green": @{kId:	@(0x3f9b0b)},
                      @"navy": @{kId:	@(0x01153e)},
                      @"aquamarine": @{kId:	@(0x04d8b2)},
                      @"burnt orange": @{kId:	@(0xc04e01)},
                      @"neon green": @{kId:	@(0x0cff0c)},
                      @"bright blue": @{kId:	@(0x0165fc)},
                      @"rose": @{kId:	@(0xcf6275)},
                      @"light pink": @{kId:	@(0xffd1df)},
                      @"mustard": @{kId:	@(0xceb301)},
                      @"indigo": @{kId:	@(0x380282)},
                      @"lime": @{kId:	@(0xaaff32)},
                      @"sea green": @{kId:	@(0x53fca1)},
                      @"periwinkle": @{kId:	@(0x8e82fe)},
                      @"dark pink": @{kId:	@(0xcb416b)},
                      @"olive green": @{kId:	@(0x677a04)},
                      @"peach": @{kId:	@(0xffb07c)},
                      @"pale green": @{kId:	@(0xc7fdb5)},
                      @"light brown": @{kId:	@(0xad8150)},
                      @"hot pink": @{kId:	@(0xff028d)},
                      @"black": @{kId:	@(0x000000)},
                      @"lilac": @{kId:	@(0xcea2fd)},
                      @"navy blue": @{kId:	@(0x001146)},
                      @"royal blue": @{kId:	@(0x0504aa)},
                      @"beige": @{kId:	@(0xe6daa6)},
                      @"salmon": @{kId:	@(0xff796c)},
                      @"olive": @{kId:	@(0x6e750e)},
                      @"maroon": @{kId:	@(0x650021)},
                      @"bright green": @{kId:	@(0x01ff07)},
                      @"dark purple": @{kId:	@(0x35063e)},
                      @"mauve": @{kId:	@(0xae7181)},
                      @"forest green": @{kId:	@(0x06470c)},
                      @"aqua": @{kId:	@(0x13eac9)},
                      @"cyan": @{kId:	@(0x00ffff)},
                      @"tan": @{kId:	@(0xd1b26f)},
                      @"dark blue": @{kId:	@(0x00035b)},
                      @"lavender": @{kId:	@(0xc79fef)},
                      @"turquoise": @{kId:	@(0x06c2ac)},
                      @"dark green": @{kId:	@(0x033500)},
                      @"violet": @{kId:	@(0x9a0eea)},
                      @"light purple": @{kId:	@(0xbf77f6)},
                      @"lime green": @{kId:	@(0x89fe05)},
                      @"grey": @{kId:	@(0x929591)},
                      @"sky blue": @{kId:	@(0x75bbfd)},
                      @"yellow": @{kId:	@(0xffff14)},
                      @"magenta": @{kId:	@(0xc20078)},
                      @"light green": @{kId:	@(0x96f97b)},
                      @"orange": @{kId:	@(0xf97306)},
                      @"teal": @{kId:	@(0x029386)},
                      @"light blue": @{kId:	@(0x95d0fc)},
                      @"red": @{kId:	@(0xe50000)},
                      @"brown": @{kId:	@(0x653700)},
                      @"pink": @{kId:	@(0xff81c0)},
                      @"blue": @{kId:	@(0x0343df)},
                      @"green": @{kId:	@(0x15b01a)},
                      @"purple": @{kId:	@(0x7e1e9c)},
                      };
}

- (NSString *)nameForColor:(UIColor *)color {
    
    CGFloat iR = 0.0f;
    CGFloat iG = 0.0f;
    CGFloat iB = 0.0f;
    CGFloat iA = 0.0f;
    
    [color getRed:&iR green:&iG blue:&iB alpha:&iA];
    
    CGFloat minDistance = CGFLOAT_MAX;
    NSString *colorKey = nil;
    
    for (NSString *key in self.colorMap) {
        @autoreleasepool {
            UIColor *currentColor = [self colorFromRGBFloat:[self.colorMap[key][kId] intValue]];
           
            CGFloat cR, cG, cB, cA = 0.0f;
            [currentColor getRed:&cR green:&cG blue:&cB alpha:&cA];
           
            // Calculate euclidean distance
            
            // Deltas
            CGFloat dR = iR - cR;
            CGFloat dG = iG - cG;
            CGFloat dB = iB - cB;
            
            CGFloat a = pow(dR, 2.0f);
            CGFloat b = pow(dG, 2.0f);
            CGFloat c = pow(dB, 2.0f);
            
            CGFloat d = sqrt(a + b + c);
            
            if (d < minDistance) {
                minDistance = d;
                colorKey = key;
            }
        }
    }
    return colorKey;
}


@end
